### ISSUE TITLE
Freezes after "Starting OpenVAS"

### ISSUE THREAD

**Issue by turkmenkaan** [TheDoctor0/openvas-docker-lite#8]
Thanks for the repo. This seems like exactly what I needed considering how most other OpenVAS images are not being maintained anymore. However, when I try running 

`docker run --rm -d -v $(pwd)/reports:/reports/:rw thedoctor0/openvas-docker-lite python3 -u scan.py 127.0.0.1`

It outputs `Starting OpenVAS` and freezes. I left it on for more than 3 hours the other day. I'm trying to scan another Linux distribution on another container.

Any ideas what might be going wrong?

**Comment by TheDoctor0** [comment]
Hi @turkmenkaan.
Info "Starting OpenVAS" indicates that services are starting and Redis plugin cache is being rebuilt.
Normally it should take no more than 5-15 minutes and it really depends on your Docker setup.

If you have any problems, you can jump into the running container using `docker exec -it <container> bash` and check logs in `/usr/local/var/log/gvm`.
