### ISSUE TITLE
Profiles don't work

### ISSUE THREAD

**Issue by turkmenkaan** [TheDoctor0/openvas-docker-lite#9]
Hi,

When I try to run a scan with any profile other than the default profile, I get an error.

Here is the command I run

`python3 -u scan.py [IP] -f PDF -o scan.pdf -p "Full and very deep"`

and the result I got was this

```
Starting OpenVAS...
Starting scan with settings:
* Target: [IP]
* Excluded hosts: 
* Scan profile: Full and very deep
* Scan ports: All TCP and Nmap top 100 UDP
* Alive tests: ICMP, TCP-ACK Service & ARP Ping
* Max hosts: 10
* Max checks: 3
* Report format: PDF
* Output file: scan.pdf

Performed initial cleanup.
Created target with id: 906b66b7-4970-449a-9f07-7f455f1478ee.
[ERROR] Response: Response Error 404. Failed to find config '708f25c4-7489-11df-8094-002264764cea'
```

Any ideas what the reason and solution might be? 

Thanks in advance!

**Comment by TheDoctor0** [comment]
I'll have to check if profile UUIDs are still up-to-date.

**Comment by turkmenkaan** [comment]
Thanks a lot!

**Comment by TheDoctor0** [comment]
`Full and Fast` is the only one left from those four `Full and *` profiles.
Possibly they have been merged into one after `Post Lists` were added.

There are also some new profiles that seem to be for policy compliance checks.

**Comment by TheDoctor0** [comment]
Profile list has been updated: https://github.com/TheDoctor0/openvas-docker-lite/commit/49f4c16e57e02bdf26de88fc34ef385a6d394db0
The container image is being rebuilt.
